### ISSUE TITLE
HTTPS no linkedin

### ISSUE THREAD

**Issue by neuberoliveira** [nathanccoelho/nathanccoelho#1]
faltou o `https` no link do likedin ai sem isso entente que um caminho relativo e fica um link nada a ver `https://github.com/nathanccoelho/nathanccoelho/blob/main/www.linkedin.com/in/nathan-ccoelho`

**Comment by nathanccoelho** [comment]
Opa, bom dia! Valeu vou alterar.

Em qui., 21 de set. de 2023 às 10:49, Neuber Oliveira <
***@***.***> escreveu:
